#file: noinspection DartPathPackageReference
name: lhw
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  responsive_framework: ^1.1.1
  animated_bottom_navigation_bar: ^1.2.1
  circular_reveal_animation: ^2.0.1
  flutter_svg: ^2.0.7
  dropdown_button2:
    path: dropdown_button2-2.3.9
  fl_chart: ^0.63.0
  circle_progress_bar: ^0.1.2
  dashed_circular_progress_bar: ^0.0.4
  percent_indicator: ^4.2.3
  simple_progress_indicators: ^0.2.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  flip_card: ^0.7.0
  flick_video_player: ^0.5.0
  google_fonts: ^6.0.0
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.2.1
  animations: ^2.0.8
  floor: ^1.4.2
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
  mockito: ^5.4.2
  sqflite: ^2.3.0
  syncfusion_flutter_charts:
    path: syncfusion_flutter_charts-23.1.36
  path_provider: ^2.1.2
  flutter_calendar_carousel: ^2.4.2
  progresso: ^0.3.0
  expandable: ^5.0.1
  fluttertoast: any
  firebase_storage: ^11.6.2
  firebase_auth: ^4.17.1
  firebase_core: ^2.25.1
  cloud_firestore: ^4.15.1
  pin_code_fields: ^8.0.1
  get: ^4.6.6
  photo_view: ^0.14.0
  pinch_zoom: ^1.0.0
  flutter_phone_number_field:
    path: flutter_phone_number_field-1.0.1
  buttons_tabbar:
    path: buttons_tabbar-1.3.7+1
  loading_animation_widget: ^1.2.0+4
  firebase_messaging: ^14.6.9
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  open_file: ^3.3.2
  http: ^1.2.0
  permission_handler: ^11.2.0
  dio: ^5.4.0
  flutter_secure_storage: ^8.1.0
  audioplayers: ^5.2.1
  flutter_animate: ^4.5.0
  draggable_fab: ^0.1.4
  flutter_animated_dialog: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/test/
    - assets/script11/
    - assets/objectivesTree/
    - assets/sounds/

  fonts:
    - family: UrduType
      fonts:
        - asset: assets/fonts/nastaliq.ttf
