import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_phone_number_field/flutter_phone_number_field.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:get/get.dart';

import '../models/user_model.dart';
import 'Login.dart';

class SignUpScreen extends StatefulWidget {
  const SignUpScreen({super.key});

  @override
  State<SignUpScreen> createState() => _SignUpScreenState();
}

class _SignUpScreenState extends State<SignUpScreen> {
  bool _obscureText = true;
  bool _isChecked = false;
  final TextEditingController nameController = TextEditingController();
  final TextEditingController emailController = TextEditingController();
  final TextEditingController phoneController = TextEditingController();
  final TextEditingController nicController = TextEditingController();
  final TextEditingController idNoController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();
  DateTime? selectedDate;

  void _signup() async {
    String dobFormatted = selectedDate != null
        ? "${selectedDate!.year.toString().padLeft(4, '0')}-${selectedDate!.month.toString().padLeft(2, '0')}-${selectedDate!.day.toString().padLeft(2, '0')}"
        : "";

    String currentTime = DateTime.now().toIso8601String();

    User newUser = User(
      id: 0, // ID should be generated by your backend/database
      name: nameController.text,
      email: emailController.text,
      phone: phoneController.text,
      nic: nicController.text,
      idNo: idNoController.text,
      dob: dobFormatted,
      village: "", // Assuming default or empty for now
      ucName: "", // Assuming default or empty for now
      yearsExperience: 0, // Assuming default or zero for now
      emailVerifiedAt:
          null, // Assuming null for now, set accordingly if applicable
      password: passwordController.text,
      image:
          "", // Assuming default or empty for now, set accordingly if applicable
      roleId: null, // Assuming null for now, set accordingly if applicable
      status: "active", // Assuming 'active' as default status for new users
      rememberToken:
          null, // Assuming null for now, set accordingly if applicable
      createdAt: currentTime,
      updatedAt: currentTime,
    );

    // Convert the newUser object to a JSON string
    String newUserJson = json.encode(newUser.toJson());
    print(newUserJson);

    // Here you would send newUserJson to your backend or database for storage
    // This step would involve using an HTTP client or your backend API

    @override
    void dispose() {
      nameController.dispose();
      emailController.dispose();
      phoneController.dispose();
      nicController.dispose();
      idNoController.dispose();
      passwordController.dispose();
      super.dispose();
    }

// The rest of your widget build method and other utility methods...
  }

  Future<void> _selectDate(BuildContext context) async {
    DateTime? selectedDate = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(1900),
      lastDate: DateTime.now(),
    );

    if (selectedDate != null && selectedDate != DateTime.now()) {
      // Get the instance of SignUpController

      // Format the selected date and set it to the dob controller of SignUpController
    }
  }

  void _toggleVisibility() {
    setState(() {
      _obscureText = !_obscureText;
    });
  }

  @override
  Widget build(BuildContext context) {
    final _formkey = GlobalKey<FormState>();

    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.only(left: 15, right: 15, top: 60),
        child: Directionality(
          textDirection: TextDirection.ltr,
          child: Form(
            key: _formkey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                const Center(
                    child: Text(
                  "ارے وہاں",
                  style: TextStyle(fontFamily: "UrduType", fontSize: 30),
                )),
                Directionality(
                  textDirection: TextDirection.rtl,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Text(
                        "پہلے سے جانتے ہیں؟",
                        style: TextStyle(
                            fontFamily: "UrduType",
                            fontSize: 20,
                            color: Color(0xff878787)),
                      ),
                      GestureDetector(
                        onTap: () {
                          Get.back;
                        },
                        child: const Text(
                          "لاگ ان کریں",
                          style: TextStyle(
                              fontFamily: "UrduType",
                              fontSize: 20,
                              color: Color(0xffFE8BD1)),
                        ),
                      ),
                      const Text(
                        "LHW",
                        style: TextStyle(
                            fontFamily: "UrduType",
                            fontSize: 20,
                            color: Color(0xff878787)),
                      ),
                    ],
                  ),
                ),
                Expanded(
                    child: ListView(
                  children: [
                    const Directionality(
                      textDirection: TextDirection.rtl,
                      child: Text(
                        "نام",
                        style: TextStyle(
                            fontFamily: "UrduType",
                            fontSize: 16,
                            color: Color(0xff0F0D18)),
                      ),
                    ),
                    const SizedBox(
                      height: 5,
                    ),
                    TextField(
                      controller: nameController,
                      decoration: InputDecoration(
                        contentPadding: const EdgeInsets.symmetric(
                            vertical: 10.0,
                            horizontal: 10.0), // Adjust vertical padding
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xfff28bc9),
                            width: 2,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    const Directionality(
                      textDirection: TextDirection.rtl,
                      child: Text(
                        "ای میل",
                        style: TextStyle(
                            fontFamily: "UrduType",
                            fontSize: 16,
                            color: Color(0xff0F0D18)),
                      ),
                    ),
                    const SizedBox(
                      height: 5,
                    ),
                    TextField(
                      controller: emailController,
                      keyboardType: TextInputType.emailAddress,
                      decoration: InputDecoration(
                        contentPadding: const EdgeInsets.symmetric(
                            vertical: 10.0,
                            horizontal: 10.0), // Adjust vertical padding
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xfff28bc9),
                            width: 2,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    Container(
                      alignment: Alignment.centerRight,
                      child: RichText(
                        text: const TextSpan(
                          text: '*',
                          style: TextStyle(
                            color: Color(
                                0xffEC5A53), // This makes the asterisk red
                            fontSize: 16,
                          ),
                          children: <TextSpan>[
                            TextSpan(
                              text: 'فون نمبر',
                              style: TextStyle(
                                fontFamily: "UrduType",
                                color: Colors
                                    .black, // Change the color as you want
                                fontSize: 16,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 5,
                    ),
                    FlutterPhoneNumberField(
                      controller: phoneController,
                      showCountryFlag: true,
                      showDropdownIcon: false,
                      initialCountryCode: "PK",
                      pickerDialogStyle: PickerDialogStyle(
                        countryFlagStyle: const TextStyle(fontSize: 17),
                      ),
                      decoration: InputDecoration(
                        contentPadding: EdgeInsets.symmetric(
                            vertical: 10.0, horizontal: 10.0),
                        hintText: 'اپنا موبائل نمبر درج کیجئے',
                        hintStyle: TextStyle(
                          fontFamily: "UrduType",
                          color: Color(0xff7A7D84),
                        ),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xfff28bc9),
                            width: 2,
                          ),
                        ),
                      ),
                      languageCode: "ar",
                      onChanged: (phone) {},
                      onCountryChanged: (country) {},
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    Container(
                      alignment: Alignment.centerRight,
                      child: RichText(
                        text: const TextSpan(
                          text: '*',
                          style: TextStyle(
                            color: Color(
                                0xffEC5A53), // This makes the asterisk red
                            fontSize: 16,
                          ),
                          children: <TextSpan>[
                            TextSpan(
                              text: 'لیڈی ہیلتھ ورکر کا شناختی نمبر',
                              style: TextStyle(
                                fontFamily: "UrduType",
                                color: Colors
                                    .black, // Change the color as you want
                                fontSize: 16,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 5,
                    ),
                    TextField(
                      controller: idNoController,
                      decoration: InputDecoration(
                        contentPadding: const EdgeInsets.symmetric(
                            vertical: 10.0,
                            horizontal: 10.0), // Adjust vertical padding
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xfff28bc9),
                            width: 2,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    Container(
                      alignment: Alignment.centerRight,
                      child: RichText(
                        text: const TextSpan(
                          text: '*',
                          style: TextStyle(
                            color: Color(
                                0xffEC5A53), // This makes the asterisk red
                            fontSize: 16,
                          ),
                          children: <TextSpan>[
                            TextSpan(
                              text: 'شناختی کارڈ نمبر',
                              style: TextStyle(
                                fontFamily: "UrduType",
                                color: Colors
                                    .black, // Change the color as you want
                                fontSize: 16,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 5,
                    ),
                    TextField(
                      controller: nicController,
                      decoration: InputDecoration(
                        contentPadding: const EdgeInsets.symmetric(
                            vertical: 10.0,
                            horizontal: 10.0), // Adjust vertical padding
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xfff28bc9),
                            width: 2,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    Container(
                      alignment: Alignment.centerRight,
                      child: RichText(
                        text: const TextSpan(
                          text: '*',
                          style: TextStyle(
                            color: Color(
                                0xffEC5A53), // This makes the asterisk red
                            fontSize: 16,
                          ),
                          children: <TextSpan>[
                            TextSpan(
                              text: 'پاس ورڈ',
                              style: TextStyle(
                                fontFamily: "UrduType",
                                color: Colors
                                    .black, // Change the color as you want
                                fontSize: 16,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 5,
                    ),
                    TextField(
                        controller: passwordController,
                        obscureText: _obscureText,
                        decoration: InputDecoration(
                          suffixIcon: IconButton(
                            icon: Icon(
                              _obscureText
                                  ? Icons.remove_red_eye_outlined
                                  : Icons.remove_red_eye,
                              color: Colors.black,
                            ),
                            onPressed: _toggleVisibility,
                          ),
                          contentPadding: const EdgeInsets.symmetric(
                            vertical: 10.0,
                            horizontal: 10.0,
                          ),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8.0),
                            borderSide: const BorderSide(
                              color: Color(0xffCDD1E0),
                            ),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8.0),
                            borderSide: const BorderSide(
                              color: Color(0xffCDD1E0),
                            ),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8.0),
                            borderSide: const BorderSide(
                              color: Color(0xfff28bc9),
                              width: 2,
                            ),
                          ),
                        )),
                    const SizedBox(
                      height: 20,
                    ),
                    Container(
                      alignment: Alignment.centerRight,
                      child: RichText(
                        text: const TextSpan(
                          text: '*',
                          style: TextStyle(
                            color: Color(
                                0xffEC5A53), // This makes the asterisk red
                            fontSize: 16,
                          ),
                          children: <TextSpan>[
                            TextSpan(
                              text: 'تاریخ پیدائش',
                              style: TextStyle(
                                fontFamily: "UrduType",
                                color: Colors
                                    .black, // Change the color as you want
                                fontSize: 16,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 5,
                    ),
                    GestureDetector(
                        child: TextField(
                      readOnly: true,
                      decoration: InputDecoration(
                        hintText: "MM/DD/YYYY",
                        suffixIcon: IconButton(
                          icon: const Icon(Icons.calendar_today_outlined,
                              color: Colors.black),
                          onPressed: () {
                            _selectDate(context);
                          },
                        ),
                        contentPadding: const EdgeInsets.symmetric(
                          vertical: 10.0,
                          horizontal: 10.0,
                        ),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xffCDD1E0),
                          ),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8.0),
                          borderSide: const BorderSide(
                            color: Color(0xfff28bc9),
                            width: 2,
                          ),
                        ),
                      ),
                    )),
                    const SizedBox(
                      height: 20,
                    ),
                    const SizedBox(
                      height: 10,
                    ),
                    Directionality(
                      textDirection: TextDirection.rtl,
                      child: Row(
                        children: [
                          CustomCheckbox(
                            value: _isChecked,
                            onChanged: (value) {
                              setState(() {
                                _isChecked = value!;
                              });
                            },
                          ),
                          const SizedBox(
                            width: 10,
                          ),
                          const Text(
                            "مجھے پہچانتے ہو",
                            style: TextStyle(
                                fontFamily: "UrduType",
                                fontSize: 16,
                                color: Color(0xff0F0D18)),
                          ),
                        ],
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.only(top: 15.0, bottom: 15.0),
                      child: RoundedButton(
                          title: 'Signup',
                          onTap: () {
                            _signup();
                          }),
                    )
                  ],
                ))
              ],
            ),
          ),
        ),
      ),
    );
  }

  bool areFieldsEmpty(List<TextEditingController> controllers) {
    for (var controller in controllers) {
      if (controller.text.trim().isEmpty) {
        return true;
      }
    }
    return false;
  }
}

class CustomCheckbox extends StatefulWidget {
  final bool value;
  final ValueChanged<bool?> onChanged;

  CustomCheckbox({required this.value, required this.onChanged});

  @override
  _CustomCheckboxState createState() => _CustomCheckboxState();
}

class _CustomCheckboxState extends State<CustomCheckbox> {
  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        widget.onChanged(!widget.value);
      },
      child: Container(
        width: 24.0,
        height: 24.0,
        decoration: BoxDecoration(
          border: Border.all(width: 1.0, color: const Color(0xffE5E5E5)),
          borderRadius: BorderRadius.circular(4.0),
        ),
        child: widget.value ? const Icon(Icons.check, size: 20.0) : null,
      ),
    );
  }
}
